### PR TITLE
fix: delete 'rm -rf /var/sd-workspaces/${ID_WITH_PREFIX}'

### PR DESCRIPTION
**Pull request by tk3fftk**
## Context
Cleanup under `/var/sd-workspaces` is no longer needed because of we haven't used the directory since https://github.com/screwdriver-cd/hyperctl-image/commit/c889d81a874ea48b1a51469d0956a8eb26cb5956 .

## Objective
Delete `rm -rf /var/sd-workspaces/${ID_WITH_PREFIX}` command.
And do some refactor with [shellcheck](https://github.com/koalaman/shellcheck).

## References
- [SC2006 · koalaman/shellcheck Wiki](https://github.com/koalaman/shellcheck/wiki/SC2006)
- [SC2086 · koalaman/shellcheck Wiki](https://github.com/koalaman/shellcheck/wiki/SC2086)

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by tk3fftk** [comment]
hypercontainer is missing...
```
$ curl https://hypercontainer-download.s3-us-west-1.amazonaws.com/0.8/centos/hyper-container-0.8.1-1.el7.centos.x86_64.rpm
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>hypercontainer-download</BucketName><RequestId>BA248CD854083A39</RequestId><HostId>sEfFCUhLz8Bjfwd4kr9vrHfyqwdyanld6UkY/fjTnCwCJ6qV4ECldfWmHYBempipzc5YG8u4gRs=</HostId></Error>
```

**Comment by tk3fftk** [comment]
Need https://github.com/screwdriver-cd/hyperctl-image/pull/30 before this PR

**Comment by jithine** [comment]
@tk3fftk please rebase this against master. PR 30 got merged

**Comment by tk3fftk** [comment]
@jithin1987 done :pray:

**Review by jithine — APPROVED** [review]

**Pull request merged**
